# Menus
# 导航栏菜单，可以添加多个选项,这里默认是英文，可以到中文中去寻找对应的意思
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Category: /abc
    uncategorized: /bcd
    About: /about/index.html

# Customize
customize:
    logo:
        width: 165
        height: 60
	#在source中，默认是那个hueman,背景透明
        url: images/fangzh.png
    theme_color: '#0087deb5'
    highlight: androidstudio
    sidebar: left # sidebar position, options: left, right
	#缩略图,在每个文章的front-matter中可以添加，如果没有添加，默认为第一张
    thumbnail: true # enable posts thumbnail, options: true, false
	#站点图标
    favicon: favicon_1.ico # path to favicon 在theme的根目录下
	#社交平台,由其他的小图标
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
       # twitter: /
       # facebook: /
       # google-plus: /
        github: https://github.com/ZJUFangzh
       # weibo: /
        #weixin: https://www.zhihu.com/people/fang-ze-hua-56/
        rss: /atom.xml
        #知乎图标不显示
        #zhihu: https://www.zhihu.com/people/fang-ze-hua-56/

 
# Widgets
#左边栏一些小标签
widgets:
    - catalog
    - recent_posts
    - communication
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
#评论系统
comment:
    disqus: hexo-theme-hueman # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # options for isso. All fields below are OPTIONAL (except for site). See https://posativ.org/isso/docs/configuration/client/ for more information.
        on: # enter true to enable isso
        site: # enter the domain name of your own comment isso server, eg. comments.example.com
        lang: # two letter language code, eg. en
        reply-to-self: # true when your server spam guard has this value set
        require-author: # true when your server spam guard has this value set
        require-email: # true when your server spam guard has this value set
        max-comments-top: # number of top level comments to show, specify "inf" for all
        max-comments-nested: # number of nested comments to show.
        reveal-on-click: # number of comments to reveal when clicking "hidden" link
        avatar: # true|false, setting to enable avatar generation
        avatar-bg: # background color of avatar, i.e. "#f0f0f0"
        avatar-fg: # set pallet of foreground colors (up to 8) i.e. "#9abf88 #5698c4 #e279a3 #9163b6"
        vote: # true|false, setting to enable voting feature on client side.
        vote-levels: # levels to customize appearance of comments, eg. "[-5, 5, 15]" or "0,5,10"
    changyan:
        appId: # enter the changyan appId here
        appKey: # enter the changyan appKey here
        on: # enter true to enable
    valine: # Valine Comment System https://github.com/xCss/Valine
        on:  # enter true to enable valine
        appId:  # enter the leancloud application appId here
        appKey:  # enter the leancloud application appKey here
        notify: # enter true to enable <Mail notifier> https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
        verify: # enter true to enable <Validation code>
        placeholder: Just Do It # enter the comment box placeholder
        avatar: identicon # (''/mm/identicon/monsterid/wavatar/retro/hide), more to see https://valine.js.org/avatar/
        avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
        pageSize: 10 # comments of one page

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key
    bing_site_verification: # enter Bing verification key here
    statcounter:
      sc_project: # enter statcounter project id
      sc_invisible: # enter 1 to make statcounter invisible
      sc_security: # enter security code
      public: # enter true if you want a link to your public stats. Must be configured on statcouter as well.
      on: # enter true to enable statcounter
    mathjax: false # options: true, false

#其他
# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me ，不知道干嘛，好像是关联fb的
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        #zhihu: http://www.qq.com
        #qq: https://www.zhihu.com
        Hexo: http://hexo.io










